# Generated by Django 3.2.5 on 2022-07-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keijiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadmodel',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='threadmodel',
            name='updated_time',
        ),
    ]
