# Generated by Django 3.2.5 on 2022-07-10 04:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('keijiapp', '0002_auto_20220704_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmodel',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threadmodel',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
